# Generated by Django 5.2.8 on 2025-11-06 17:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('senha_hash', models.CharField(max_length=128)),
                ('matricula', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('cr_geral', models.FloatField()),
                ('curso', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('senha_hash', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Casa (Administrador)',
                'verbose_name_plural': 'Casa (Administradores)',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('senha_hash', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('aluno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.aluno')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
            bases=('myapp.aluno',),
        ),
        migrations.CreateModel(
            name='MonitorTEA',
            fields=[
                ('aluno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.aluno')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Monitor TEA',
                'verbose_name_plural': 'Monitores TEA',
            },
            bases=('myapp.aluno',),
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('professor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.professor')),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
            },
            bases=('myapp.professor',),
        ),
        migrations.CreateModel(
            name='VagaMonitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('pre_requisitos', models.TextField()),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada'), ('Em Análise', 'Em Análise')], default='Aberta', max_length=20)),
                ('prazo_inscricao', models.DateField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='myapp.disciplina')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_cadastradas', to='myapp.coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentos', models.TextField()),
                ('cr_disciplina', models.FloatField(default=0.0, help_text='CR (Coeficiente de Rendimento) na disciplina da vaga')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada')], default='Pendente', max_length=20)),
                ('data_candidatura', models.DateField(default=datetime.date.today)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas_realizadas', to='myapp.aluno')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas_recebidas', to='myapp.vagamonitoria')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMonitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_monitoria', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('codigo_disciplina', models.CharField(max_length=20)),
                ('descricao_atividade', models.TextField(help_text='O que foi ensinado/abordado na monitoria')),
                ('alunos_participantes', models.JSONField(default=list, help_text="Lista de dicionários com 'matricula' e 'nome' dos alunos participantes")),
                ('quantidade_alunos', models.IntegerField(default=0)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_atividade', to='myapp.candidatura')),
                ('monitor_tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_monitorias', to='myapp.monitortea')),
            ],
            options={
                'verbose_name': 'Registro de Monitoria',
                'verbose_name_plural': 'Registros de Monitoria',
                'ordering': ['-data_monitoria'],
            },
        ),
    ]
