# Generated by Django 5.2.8 on 2025-11-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagamonitoria',
            name='tipo_monitoria',
            field=models.CharField(choices=[('Monitor', 'Monitor (Voluntário)'), ('MonitorTEA', 'Monitor TEA (Remunerado)')], default='Monitor', help_text='Tipo de monitoria: Monitor voluntário ou Monitor TEA remunerado', max_length=20),
        ),
    ]
