# Generated by Django 5.2.8 on 2025-11-12 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vagamonitoria_tipo_monitoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagamonitoria',
            name='casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_criadas', to='myapp.casa'),
        ),
    ]
