# Generated by Django 5.2.7 on 2025-10-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('cr_geral', models.DecimalField(decimal_places=1, max_digits=2)),
                ('cr_disciplina', models.DecimalField(decimal_places=1, max_digits=3)),
                ('curso', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.IntegerField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('documentos', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=20)),
                ('data_candidatura', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('senha', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMonitoria',
            fields=[
                ('id', models.IntegerField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_registro', models.DateField()),
                ('validacao', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('id', models.IntegerField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('pre_requisitos', models.TextField()),
                ('disciplina', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=20)),
                ('prazo_inscricao', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
